# Generated by Django 6.0.2 on 2026-03-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_show', '0002_rename_show_shows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
